# Generated by Django 5.2 on 2026-01-06 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orbit',
            fields=[
                ('orbit_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estimated_cycles', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('cycle_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(default=None)),
                ('end_time', models.DateTimeField(default=None, null=True)),
                ('work_duration', models.TimeField(default=None)),
                ('rest_duration', models.TimeField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused')], default='in_progress')),
                ('orbit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.orbit')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task')),
            ],
        ),
    ]
