# Generated by Django 5.2 on 2026-02-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Default',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_duration', models.TimeField(default='00:25:00')),
                ('rest_duration', models.TimeField(default='00:05:00')),
                ('orbit_cylces', models.IntegerField(default=2)),
            ],
        ),
    ]
